### ISSUE TITLE
sitemap.xml contains URLs to localhost

### ISSUE THREAD

**Issue by gildesmarais** [signdict/blog#1]
The [sitemap.xml](https://blog.signdict.org/sitemap.xml) contains links to `localhost:4000/about/`. If you're using the sitemap, I'm sure search engines will not like these URLs.

Also, I noticed [a missing robots.txt](http://blog.signdict.org/robots.txt) (not really an issue, just mentioning it).

**Comment by bitboxer** [comment]
Thanks! Fixed it 👍 . And the missing robots is not an issue for me. Let the robots robot the page 🤖
